<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Ejemplos | El Teorema de Bayes con Diagramas de Venn</title>
  <meta name="description" content="Explicaciones del Teorema de Bayes" />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Ejemplos | El Teorema de Bayes con Diagramas de Venn" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://seankross.com/bookdown-start/" />
  
  <meta property="og:description" content="Explicaciones del Teorema de Bayes" />
  <meta name="github-repo" content="juliosergio/miniBayes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Ejemplos | El Teorema de Bayes con Diagramas de Venn" />
  
  <meta name="twitter:description" content="Explicaciones del Teorema de Bayes" />
  

<meta name="author" content="Julio Sergio Santana" />


<meta name="date" content="2019-06-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="teorema-de-bayes-explicado.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Teorema de Bayes con Diagramas de Venn</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prólogo</a></li>
<li class="chapter" data-level="1" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html"><i class="fa fa-check"></i><b>1</b> Teorema de Bayes Explicado</a><ul>
<li class="chapter" data-level="1.1" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html#el-teorema-de-bayes"><i class="fa fa-check"></i><b>1.1</b> El teorema de Bayes</a></li>
<li class="chapter" data-level="1.2" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html#explicacion-grafica-del-teorema"><i class="fa fa-check"></i><b>1.2</b> Explicación gráfica del teorema</a><ul>
<li class="chapter" data-level="1.2.1" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html#situacion-inicial"><i class="fa fa-check"></i><b>1.2.1</b> Situación inicial</a></li>
<li class="chapter" data-level="1.2.2" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html#el-teorema-de-la-probabilidad-total"><i class="fa fa-check"></i><b>1.2.2</b> El teorema de la probabilidad total</a></li>
<li class="chapter" data-level="1.2.3" data-path="teorema-de-bayes-explicado.html"><a href="teorema-de-bayes-explicado.html#el-teorema-de-bayes-deduccion-y-explicacion-analitica"><i class="fa fa-check"></i><b>1.2.3</b> El teorema de Bayes: deducción y explicación analítica</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ejemplos.html"><a href="ejemplos.html"><i class="fa fa-check"></i><b>2</b> Ejemplos</a><ul>
<li class="chapter" data-level="2.1" data-path="ejemplos.html"><a href="ejemplos.html#ejemplo-1"><i class="fa fa-check"></i><b>2.1</b> Ejemplo 1</a><ul>
<li class="chapter" data-level="" data-path="ejemplos.html"><a href="ejemplos.html#solucion"><i class="fa fa-check"></i>Solución</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="ejemplos.html"><a href="ejemplos.html#ejemplo-2"><i class="fa fa-check"></i><b>2.2</b> Ejemplo 2</a><ul>
<li class="chapter" data-level="" data-path="ejemplos.html"><a href="ejemplos.html#solucion-1"><i class="fa fa-check"></i>Solución</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">El Teorema de Bayes con Diagramas de Venn</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ejemplos" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Ejemplos</h1>
<div id="ejemplo-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Ejemplo 1</h2>
<p>Por razones de pagos en publicidad, un piloto de autos usa un Corvette en el 50% de las carreras en las que participa, un Jaguar, en el 30% de esas carreras y un Alfa Romeo, en el 20% de las mismas. De 25 carreras en las que ha participado con el Corvette, ha ganado 5; de 15, en las que ha participado con el Jaguar, ha ganado 4; y de 10, en las que ha participado con el Alfa Romeo, ha ganado 4.</p>
<ol style="list-style-type: lower-alpha">
<li>Haciendo uso de esa información para estimar las probabilidades, indique cuál es la probabilidad de que el piloto gane la reciente carrera en la que participará en Le Mans.</li>
<li>Suponiendo que llega la notificación de que, en efecto, ganó la carrera, ¿cuál es la probabilidad de que haya manejado el Corvette?</li>
</ol>
<p>NOTA: Este ejemplo fue tomado de los ejercicios del libro de <span class="citation">Miller and Freund (<a href="#ref-Miller65">1965</a>)</span> pp. 32-34.</p>
<div id="solucion" class="section level3 unnumbered">
<h3>Solución</h3>
<p>La Figura <a href="ejemplos.html#fig:Autos1">2.1</a> representa esquemáticamente algunos de los elementos del problema, en esta figura:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(S\)</span> representa el conjunto de todas las carreras que ha corrido el piloto.</li>
<li><span class="math inline">\(B_c\)</span> son las carreras en las que ha usado el Corvette.</li>
<li><span class="math inline">\(B_j\)</span> son las carreras en las que ha usado el Jaguar.</li>
<li><span class="math inline">\(B_a\)</span> son las carreras en las que ha usado el Alfa Romeo.</li>
<li><span class="math inline">\(A\)</span> representa el conjunto de carreras en las que ha ganado.</li>
</ol>
<div class="figure"><span id="fig:Autos1"></span>
<img src="images/Autos1.png" alt="Diagrama de Venn para el problema del piloto de autos" width="60.8%" />
<p class="caption">
FIGURA 2.1: Diagrama de Venn para el problema del piloto de autos
</p>
</div>
<p>Para resolver el problema se usará el lenguaje de programación R <span class="citation">(Santana and Mateos Farfán <a href="#ref-Santana2014">2014</a>)</span>. El primer paso es la construcción de una tabla con la información</p>
<pre class="sourceCode r"><code class="sourceCode r">datos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
  <span class="co">#                 Corvette    Jaguar    Alfa_Romeo</span>
  <span class="dt">P.B         =</span>  <span class="kw">c</span>(    <span class="fl">0.5</span>   ,    <span class="fl">0.3</span>   ,    <span class="fl">0.2</span>      ), <span class="co"># P(B)</span>
  <span class="dt">P.A_B       =</span>  <span class="kw">c</span>(   <span class="dv">5</span><span class="op">/</span><span class="dv">25</span>   ,   <span class="dv">4</span><span class="op">/</span><span class="dv">15</span>   ,   <span class="dv">4</span><span class="op">/</span><span class="dv">10</span>      ), <span class="co"># P(A|B)</span>
  <span class="dt">row.names   =</span>  <span class="kw">c</span>(<span class="st">&quot;Corvette&quot;</span>, <span class="st">&quot;Jaguar&quot;</span> , <span class="st">&quot;Alfa_Romeo&quot;</span>)
)
<span class="kw">print</span>(datos)</code></pre>
<pre><code>##            P.B     P.A_B
## Corvette   0.5 0.2000000
## Jaguar     0.3 0.2666667
## Alfa_Romeo 0.2 0.4000000</code></pre>
<p>Esta misma información se puede ver en la Tabla <a href="ejemplos.html#tab:tabla-info">2.1</a>, donde la columna <strong>P.B</strong> representa la probabilidad del conjunto <span class="math inline">\(B\)</span> en el renglón correspondiente, y la columna <strong>P.A_B</strong> es la probabilidad de que se ganó la carrera dado que se usó el auto en el renglón correspondiente.</p>
<table>
<caption><span id="tab:tabla-info">Tabla 2.1: </span>Información del piloto de autos</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">P.B</th>
<th align="right">P.A_B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Corvette</td>
<td align="right">0.5</td>
<td align="right">0.2000000</td>
</tr>
<tr class="even">
<td>Jaguar</td>
<td align="right">0.3</td>
<td align="right">0.2666667</td>
</tr>
<tr class="odd">
<td>Alfa_Romeo</td>
<td align="right">0.2</td>
<td align="right">0.4000000</td>
</tr>
</tbody>
</table>
<p>La solución del inciso <strong>a</strong> del problema se obtiene por medio de la aplicación del Teorema <a href="teorema-de-bayes-explicado.html#thm:ptotal">1.2</a> de la probabilidad total. Esto es multiplicar las columnas “P.B” y “P.A_B” de la tabla anterior y sumar todos los resultados.</p>
<pre class="sourceCode r"><code class="sourceCode r">datos<span class="op">$</span>Prod &lt;-<span class="st"> </span>datos<span class="op">$</span>P.B <span class="op">*</span><span class="st"> </span>datos<span class="op">$</span>P.A_B</code></pre>
<p>El resultado de este producto se puede ver en la columna <strong>Prod</strong> de la Tabla <a href="ejemplos.html#tab:tabla-c-prod">2.2</a></p>
<table>
<caption><span id="tab:tabla-c-prod">Tabla 2.2: </span>Productos de probabilidades</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">P.B</th>
<th align="right">P.A_B</th>
<th align="right">Prod</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Corvette</td>
<td align="right">0.5</td>
<td align="right">0.2000000</td>
<td align="right">0.10</td>
</tr>
<tr class="even">
<td>Jaguar</td>
<td align="right">0.3</td>
<td align="right">0.2666667</td>
<td align="right">0.08</td>
</tr>
<tr class="odd">
<td>Alfa_Romeo</td>
<td align="right">0.2</td>
<td align="right">0.4000000</td>
<td align="right">0.08</td>
</tr>
</tbody>
</table>
<p>Ahora se procede a hacer la suma de los valores en la columna <strong>Prod</strong> de la Tabla <a href="ejemplos.html#tab:tabla-c-prod">2.2</a> con</p>
<pre class="sourceCode r"><code class="sourceCode r">(Prob.A &lt;-<span class="st"> </span><span class="kw">sum</span>(datos<span class="op">$</span>Prod))</code></pre>
<pre><code>## [1] 0.26</code></pre>
<p>Asi entonces, la <strong>probabilidad de que el piloto gane su carrera</strong> es del 26%.</p>
<p>Para resolver el inciso <strong>b</strong> del problema se aplica el Teorema <a href="teorema-de-bayes-explicado.html#thm:bayes0">1.1</a> de Bayes. En este caso es simplemente dividir el producto en el renglón correspondiente al auto “Corvette” entre la probabilidad recien obtenida, así:</p>
<pre class="sourceCode r"><code class="sourceCode r">(Prob.Corvette &lt;-<span class="st"> </span>datos[<span class="st">&quot;Corvette&quot;</span>,<span class="st">&quot;Prod&quot;</span>]<span class="op">/</span>Prob.A)</code></pre>
<pre><code>## [1] 0.3846154</code></pre>
<p>Esto es, dado que el piloto en efecto ganó la carrera, la <strong>probabilidad de que haya usado el Corvette</strong> es de 38.4615385%.</p>
</div>
</div>
<div id="ejemplo-2" class="section level2">
<h2><span class="header-section-number">2.2</span> Ejemplo 2</h2>
<p>Una empresa utiliza filtros procedentes de dos marcas de <em>software</em> para detectar correo <em>spam</em>: la marca <strong>Ms</strong>
y la marca <strong>G</strong>. Estadísticamente se ha determinado a nivel mundial que <strong>Ms</strong> clasifica correctamente
sólo el 70% de los correos como <em>spam</em> o <em>no-spam</em>, mientras que <strong>G</strong> alcanza el 98%. Sin embargo,
como la junta directiva se ha dejado llevar por la marca, ha determinado que 65% de sus correos sean
filtrados por el <em>software</em> de <strong>Ms</strong>, mientras que el resto, o sea, el 35%, sean asignados para ser filtrados por el <em>software</em> de la marca <strong>G</strong>.</p>
<ol style="list-style-type: lower-alpha">
<li>Roberto, el ingeniero de sistemas de la empresa, que es mucho más consciente de la realidad, quiere convencer
a la junta directiva de cambiar su política de asignación y para ello se ha propuesto responder a la
pregunta: ¿Cuál es la probabilidad de que un correo bien detectado, ya sea como <em>spam</em> o <em>no-spam</em>, proceda de <strong>Ms</strong>?</li>
</ol>
<div id="solucion-1" class="section level3 unnumbered">
<h3>Solución</h3>
<p>Primeramente se procede a identificar los distintos eventos del problema.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(A=\)</span> se ha clasificado correctamente el correo, ya sea como <em>spam</em> o como <em>no-spam</em>.</li>
<li><span class="math inline">\(B_{Ms}=\)</span> se ha asignado al <em>software</em> de la marca <strong>Ms</strong> para filtrar el correo.</li>
<li><span class="math inline">\(B_{G}=\)</span> se ha asignado al <em>software</em> de la marca <strong>G</strong> para filtrar el correo.</li>
</ol>
<p>La asignación total del volumen de correos por marca de <em>software</em> se muestra en la Figura <a href="ejemplos.html#fig:Correos1">2.2</a>.</p>
<div class="figure"><span id="fig:Correos1"></span>
<img src="images/Pcorreos1.png" alt="Diagrama de Venn que muestra la asignación de correos por marca de software" width="60.8%" />
<p class="caption">
FIGURA 2.2: Diagrama de Venn que muestra la asignación de correos por marca de software
</p>
</div>
<p>Por otra parte, el evento <em>A</em> que consiste en haber clasificado correctamente el correo, se muestra en relación con el universo de correos en la Figura <a href="ejemplos.html#fig:Correos2">2.3</a>.</p>
<div class="figure"><span id="fig:Correos2"></span>
<img src="images/Pcorreos2.png" alt="Diagrama de Venn que muestra el evento $A$: el correo ha sido clasificado correctamente" width="60.8%" />
<p class="caption">
FIGURA 2.3: Diagrama de Venn que muestra el evento <span class="math inline">\(A\)</span>: el correo ha sido clasificado correctamente
</p>
</div>
<p>Se hará una tabla (<em>data.frame</em>) para capturar toda la información del problema:</p>
<pre class="sourceCode r"><code class="sourceCode r">datos &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
  <span class="co">#               marca.Ms      marca.G</span>
  <span class="dt">P.B       =</span>  <span class="kw">c</span>(    <span class="fl">0.65</span>   ,    <span class="fl">0.35</span>     ),  <span class="co"># P(B)</span>
  <span class="dt">P.A_B     =</span>  <span class="kw">c</span>(    <span class="fl">0.70</span>   ,    <span class="fl">0.98</span>     ),  <span class="co"># P(A|B)</span>
  <span class="dt">row.names =</span>  <span class="kw">c</span>(<span class="st">&quot;marca.Ms&quot;</span> , <span class="st">&quot;marca.G&quot;</span>   )
)
<span class="kw">print</span>(datos)</code></pre>
<pre><code>##           P.B P.A_B
## marca.Ms 0.65  0.70
## marca.G  0.35  0.98</code></pre>
<p>Esta información se muestra en la Tabla <a href="ejemplos.html#tab:tabla-correos1">2.3</a> a continuación.</p>
<table>
<caption><span id="tab:tabla-correos1">Tabla 2.3: </span>Información distribución de correos</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">P.B</th>
<th align="right">P.A_B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>marca.Ms</td>
<td align="right">0.65</td>
<td align="right">0.70</td>
</tr>
<tr class="even">
<td>marca.G</td>
<td align="right">0.35</td>
<td align="right">0.98</td>
</tr>
</tbody>
</table>
<p>En la tabla anterior, la columna P.A_B, es <span class="math inline">\(P\left( A | B \right)\)</span>, o sea la probabilidad de que se haya clasificado bien el correo, dado que la clasificación se hizo con el <em>software</em> correspondiente al renglón de la tabla. Esto es, en términos de <em>relaciones de áreas</em>, la porción que ocupa <em>A</em> del conjunto <em>B</em> correspondiente. Esta situación se muestra gráficamente en la Figura <a href="ejemplos.html#fig:Correos3">2.4</a></p>
<div class="figure"><span id="fig:Correos3"></span>
<img src="images/Pcorreos3.png" alt="Diagrama de Venn que muestra la porción que ocupa $A$: de cada una de las áreas $B$" width="60.8%" />
<p class="caption">
FIGURA 2.4: Diagrama de Venn que muestra la porción que ocupa <span class="math inline">\(A\)</span>: de cada una de las áreas <span class="math inline">\(B\)</span>
</p>
</div>
<p>A continuación se procede a aplicar el Teorema <a href="teorema-de-bayes-explicado.html#thm:ptotal">1.2</a> de la probabilidad total. Esto es multiplicar las columnas “P.B” y “P.A_B” de la Tabla <a href="ejemplos.html#tab:tabla-correos1">2.3</a> y sumar todos los resultados.</p>
<pre class="sourceCode r"><code class="sourceCode r">datos<span class="op">$</span>Prod &lt;-<span class="st"> </span>datos<span class="op">$</span>P.B <span class="op">*</span><span class="st"> </span>datos<span class="op">$</span>P.A_B
<span class="co"># La suma de las columnas</span>
sumas &lt;-<span class="st"> </span><span class="kw">apply</span>(datos, <span class="dv">2</span>, sum)
<span class="co"># Se agrega el resultado como un renglón al final:</span>
datos[<span class="st">&quot;SUMAS&quot;</span>, ] &lt;-<span class="st"> </span>sumas</code></pre>
<p>El resultado de este producto se puede ver en la columna <strong>Prod</strong> de la Tabla <a href="ejemplos.html#tab:tabla-correos-prod">2.4</a></p>
<table>
<caption><span id="tab:tabla-correos-prod">Tabla 2.4: </span>Productos de probabilidades en el caso de correos</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">P.B</th>
<th align="right">P.A_B</th>
<th align="right">Prod</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>marca.Ms</td>
<td align="right">0.65</td>
<td align="right">0.70</td>
<td align="right">0.455</td>
</tr>
<tr class="even">
<td>marca.G</td>
<td align="right">0.35</td>
<td align="right">0.98</td>
<td align="right">0.343</td>
</tr>
<tr class="odd">
<td>SUMAS</td>
<td align="right">1.00</td>
<td align="right">1.68</td>
<td align="right">0.798</td>
</tr>
</tbody>
</table>
<p>De acuerdo con este resultado, la probabilidad de que, en general, un correo sea clasificado correctamente es
del 79.8%.</p>
<p>Para averiguar la probabilidad de que un correo bien detectado, ya sea como <em>spam</em> o <em>no-spam</em>, proceda de <strong>Ms</strong>, se aplica el Teorema <a href="teorema-de-bayes-explicado.html#thm:bayes0">1.1</a> de Bayes. Para ello se divide el producto en el renglón correspondiente a <strong>Ms</strong> entre la probabilidad recien obtenida, así:</p>
<pre class="sourceCode r"><code class="sourceCode r">(Prob.Ms &lt;-<span class="st"> </span>datos[<span class="st">&quot;marca.Ms&quot;</span>,<span class="st">&quot;Prod&quot;</span>]<span class="op">/</span>datos[<span class="st">&quot;SUMAS&quot;</span>,<span class="st">&quot;Prod&quot;</span>])</code></pre>
<pre><code>## [1] 0.5701754</code></pre>
<p>Esto es, dado que se clasificó correctamente el correo, la <strong>probabilidad de que para esta operación se haya usado el <em>software</em> de Ms</strong> es de 57.02%.</p>
<p>Después de presentar estos resultados a la junta directiva de la empresa, la respuesta que Roberto recibió no fue muy amable, como se puede ver en la ilustración de la Figura <a href="ejemplos.html#fig:Caricat1">2.5</a>.</p>
<div class="figure"><span id="fig:Caricat1"></span>
<img src="images/Prob2Caric1.png" alt="Respuesta de los directivos de la empresa" width="80.8%" />
<p class="caption">
FIGURA 2.5: Respuesta de los directivos de la empresa
</p>
</div>
<p>Aunque en un principio la respuesta lo tomó por sorpresa, en vez de desanimarse, Roberto trató de replantear el problema desde una prespectiva diferente, tal como se ilustra en la Figura <a href="ejemplos.html#fig:Caricat2">2.6</a>.</p>
<div class="figure"><span id="fig:Caricat2"></span>
<img src="images/Prob2Caric2.png" alt="El problema visto desde otra perspectiva" width="80.8%" />
<p class="caption">
FIGURA 2.6: El problema visto desde otra perspectiva
</p>
</div>
<p>Esto da lugar a la segunda parte de este problema, cuya descripción se hace en seguida:</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Determinar la probabilidad que que un correo mal clasificado, ya sea como <em>spam</em> o <em>no-spam</em>, provenga del <em>software</em> provisto por <strong>Ms</strong>.</li>
</ol>
<p>Con el propósito de responder a esta pregunta, debe notarse que ahora el tema ya no es el evento <span class="math inline">\(A\)</span> sino su complemento, <span class="math inline">\(\bar{A}\)</span>. Para resolver el problema, solamente es necesario modificar la columna “P.A_B”, de la tabla anterior, de acuerdo con los nuevos datos mostrados en la Figura <a href="ejemplos.html#fig:Correos4">2.7</a> y proceder a los cálculos correspondientes.</p>
<div class="figure"><span id="fig:Correos4"></span>
<img src="images/Pcorreos4.png" alt="Diagrama de Venn que muestra la porción que ocupa $\bar { A }$ : de cada una de las áreas $B$" width="60.8%" />
<p class="caption">
FIGURA 2.7: Diagrama de Venn que muestra la porción que ocupa <span class="math inline">\(\bar { A }\)</span> : de cada una de las áreas <span class="math inline">\(B\)</span>
</p>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#                 marca.Ms      marca.G  SUMA</span>
datos<span class="op">$</span>P.A_B &lt;-<span class="st"> </span><span class="kw">c</span>(    <span class="fl">0.30</span>   ,    <span class="fl">0.02</span>,    <span class="ot">NA</span> ) <span class="co"># P(A|B)</span>
<span class="co"># Se corrigen los productos</span>
datos<span class="op">$</span>Prod &lt;-<span class="st"> </span>datos<span class="op">$</span>P.B <span class="op">*</span><span class="st"> </span>datos<span class="op">$</span>P.A_B

<span class="co"># Se agregan las sumas corregidas como el renglón final:</span>
datos[<span class="st">&quot;SUMAS&quot;</span>, ] &lt;-<span class="st"> </span><span class="kw">apply</span>(datos[<span class="op">-</span><span class="dv">3</span>, ], <span class="dv">2</span>, sum)</code></pre>
<p>En la Tabla <a href="ejemplos.html#tab:tabla-correos-final">2.5</a> se pueden ver los resultados de estas operaciones.</p>
<table>
<caption><span id="tab:tabla-correos-final">Tabla 2.5: </span>Productos de probabilidades en el caso de correos mal clasificados</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">P.B</th>
<th align="right">P.A_B</th>
<th align="right">Prod</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>marca.Ms</td>
<td align="right">0.65</td>
<td align="right">0.30</td>
<td align="right">0.195</td>
</tr>
<tr class="even">
<td>marca.G</td>
<td align="right">0.35</td>
<td align="right">0.02</td>
<td align="right">0.007</td>
</tr>
<tr class="odd">
<td>SUMAS</td>
<td align="right">1.00</td>
<td align="right">0.32</td>
<td align="right">0.202</td>
</tr>
</tbody>
</table>
<p>Finalmente, se aplica el Teorema <a href="teorema-de-bayes-explicado.html#thm:bayes0">1.1</a> de Bayes. Para ello se divide el producto en el renglón correspondiente a <strong>Ms</strong> entre la probabilidad total, registrada el renglón “SUMAS” y columna “Prod”, así:</p>
<pre class="sourceCode r"><code class="sourceCode r">(Prob.Ms &lt;-<span class="st"> </span>datos[<span class="st">&quot;marca.Ms&quot;</span>,<span class="st">&quot;Prod&quot;</span>]<span class="op">/</span>datos[<span class="st">&quot;SUMAS&quot;</span>,<span class="st">&quot;Prod&quot;</span>])</code></pre>
<pre><code>## [1] 0.9653465</code></pre>
<p>Esto es, dado que se clasificó incorrectamente el correo, la <strong>probabilidad de que para esta operación se haya usado el <em>software</em> de Ms</strong> es de 96.53%. Con este contundente resultado, Roberto pudo convencer a la junta directiva de cambiar las proporciones de asignación de correos a las distintas marcas de <em>software</em>.</p>

<div id="refs" class="references">
<div>
<p>Miller, Irwin, and John E. Freund. 1965. <em>Probability and Statistics for Engineers</em>. 1st ed. Prentice-Hall Mathematics Series. Prentice-Hall. Englewood Cliffs, NJ, U.S.A.</p>
</div>
<div>
<p>Santana, Julio Sergio, and Efraı'n Mateos Farfán. 2014. <em>El Arte de Programar En R: Un Lenguaje Para La Estadı'stica</em>. 1st ed. Jiutepec, Mor., México: Instituto Mexicano de Tecnologı'a del Agua; Instituto Mexicano de Tecnologı'a del Agua. <a href="https://www.imta.gob.mx/biblioteca/libros">https://www.imta.gob.mx/biblioteca/libros</a>.</p>
</div>
<div>
<p>Walpole, Ronald E., Raymond H. Myers, Sharon L. Myers, and Keying Ye. 2012. <em>Probability &amp; Statistics for Engineers &amp; Scientists</em>. 9th ed. Boston, MA: Prentice Hall / Pearson Education, Inc.</p>
</div>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Miller65">
<p>Miller, Irwin, and John E. Freund. 1965. <em>Probability and Statistics for Engineers</em>. 1st ed. Prentice-Hall Mathematics Series. Prentice-Hall. Englewood Cliffs, NJ, U.S.A.</p>
</div>
<div id="ref-Santana2014">
<p>Santana, Julio Sergio, and Efraı'n Mateos Farfán. 2014. <em>El Arte de Programar En R: Un Lenguaje Para La Estadı'stica</em>. 1st ed. Jiutepec, Mor., México: Instituto Mexicano de Tecnologı'a del Agua; Instituto Mexicano de Tecnologı'a del Agua. <a href="https://www.imta.gob.mx/biblioteca/libros">https://www.imta.gob.mx/biblioteca/libros</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="teorema-de-bayes-explicado.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
